### ISSUE TITLE
Permission denied when creating a stub model

### ISSUE THREAD

**Issue by wvanheemstra** [Threagile/threagile#93]
When I run below command as per the threagile help documentation, it fails:

$ docker run --rm -it -v "$(pwd)":/app/work threagile/threagile -create-stub-model -output /app/work
panic: open /app/work/threagile-stub-model.yaml: permission denied

goroutine 1 [running]:
main.checkErr(...)
        github.com/threagile/threagile/main.go:664
main.createStubModelFile()
        github.com/threagile/threagile/main.go:3946 +0x9f
main.parseCommandlineArgs()
        github.com/threagile/threagile/main.go:3894 +0x7265
main.main()
        github.com/threagile/threagile/main.go:669 +0x13

**Comment by droppedbars** [comment]
I did some digging and it looks like a user permission error.
https://github.com/Threagile/threagile/issues/69#issuecomment-2813654645

`docker run --rm -it -u $(id -u ${USER}):$(id -g ${USER}) -v "$(pwd)":/app/work threagile/threagile -create-stub-model -output /app/work` 

should solve it.
